### PR TITLE
[ Fix ] Selecting Same Workspace Again Gives Notification About Workspace is Changed

### PR DESCRIPTION
**Pull request by Sumitwarrior7**
## Issue(s) 

Closes : #66 

Now Notification will be sent only if workspace is changed

## Reference:

[Screencast from 04-03-24 05:10:24 PM IST.webm](https://github.com/RocketChat/Apps.Notion/assets/108853577/63c8be03-ad9f-4bf1-a653-aba2cc11df85)

### CODE REVIEW

**Comment by Sumitwarrior7** [comment]
@Nabhag8848 bhiaya 
If you have any issues, please tell me

**Review by Nabhag8848 — APPROVED** [review]
LGTM @Sumitwarrior7 🚀, As this PR is small would you like to work on #41, it has been open since long and merge both PRs, particularly merge this branch to PR for #41 ?

**Comment by Sumitwarrior7** [comment]
ok @Nabhag8848 bhaiya
I 

> LGTM @Sumitwarrior7 🚀, As this PR is small would you like to work on #41, it has been open since long and merge both PRs, particularly merge this branch to PR for #41 ?

ok @Nabhag8848 bhaiya

**Comment by Spiral-Memory** [comment]
Sorry, @Nabhag8848 , @Sumitwarrior7 . I mistakenly mentioned my draft PR here. That was with respect to Issue 69

**Comment by Nabhag8848** [comment]
Hey @Sumitwarrior7 were you able to know, why comment multiline Input bug exists ?

**Comment by Sumitwarrior7** [comment]
hello @Nabhag8848 bhaiya
i am quite busy this week, so not able to work on the issue

but i will  start solving it on monday

**Comment by Nabhag8848** [comment]
> Hey @Sumitwarrior7 were you able to know, why comment multiline Input bug exists ? let us know if you need any help in understanding the working of code.

@Sumitwarrior7 gentle ping !

**Comment by Nabhag8848** [comment]
Hey @Sumitwarrior7 Merging as this is your first PR, We can merge it. You can keep on working on that issue. Thanks !

**Pull request merged**
